// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shtvgvnznqpinjbbrzjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodHZndm56bnFwaW5qYmJyemp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDIzMjcsImV4cCI6MjA2OTkxODMyN30.v2ygHBQJKuKeFyaGD5TvOUPEvK71ZeHooVJ1RBzhhWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});